
services:
  ex_db:
    image: mysql:9.2
    container_name: ex_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - ex_net

volumes:
  db_data:

networks:
  ex_net:
    driver: bridge
